import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { MeshoptSimplifier } from 'meshoptimizer';

await MeshoptSimplifier.ready;
const root = new URL('../', import.meta.url);
const manifestURL = new URL('public/models/bodyparts3d/manifest.json', root);
const manifest = JSON.parse(await readFile(manifestURL, 'utf8'));
const ratios = { skin: .22, muscles: .14, organs: .22, skeleton: .48 };
for (const [layer, info] of Object.entries(manifest.layers)) {
  const file = new URL(`public${info.url.split('?')[0]}`, root);
  const bytes = await readFile(file);
  const jsonLength = bytes.readUInt32LE(12);
  const document = JSON.parse(bytes.subarray(20, 20 + jsonLength).toString());
  const binary = bytes.subarray(28 + jsonLength);
  const oldAccessors = document.accessors;
  const oldViews = document.bufferViews;
  const arrays = [];
  let byteLength = 0;
  document.accessors = [];
  document.bufferViews = [];
  function get(index, Type, width) {
    const accessor = oldAccessors[index];
    const view = oldViews[accessor.bufferView];
    const start = (view.byteOffset || 0) + (accessor.byteOffset || 0);
    const raw = binary.subarray(start, start + accessor.count * width * Type.BYTES_PER_ELEMENT);
    return new Type(raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength));
  }
  function add(array, type, componentType, target, min, max) {
    const padding = (4 - byteLength % 4) % 4;
    if (padding) { arrays.push(Buffer.alloc(padding)); byteLength += padding; }
    const index = document.accessors.length;
    document.bufferViews.push({ buffer: 0, byteOffset: byteLength, byteLength: array.byteLength, target });
    document.accessors.push({ bufferView: index, componentType, count: array.length / (type === 'VEC3' ? 3 : 1), type, ...(min ? { min, max } : {}) });
    arrays.push(Buffer.from(array.buffer, array.byteOffset, array.byteLength));
    byteLength += array.byteLength;
    return index;
  }
  let triangles = 0;
  for (const mesh of document.meshes) {
    const primitive = mesh.primitives[0];
    const positions = get(primitive.attributes.POSITION, Float32Array, 3);
    const normals = get(primitive.attributes.NORMAL, Float32Array, 3);
    const indices = get(primitive.indices, Uint32Array, 1);
    const target = Math.min(indices.length, Math.max(300, Math.floor(indices.length * ratios[layer] / 3) * 3));
    const [simplified, error] = MeshoptSimplifier.simplify(indices, positions, 3, target, .005);
    const [remap, count] = MeshoptSimplifier.compactMesh(simplified);
    const p = new Float32Array(count * 3), n = new Float32Array(count * 3);
    for (let old = 0; old < remap.length; old++) {
      if (remap[old] === 0xffffffff) continue;
      p.set(positions.subarray(old * 3, old * 3 + 3), remap[old] * 3);
      n.set(normals.subarray(old * 3, old * 3 + 3), remap[old] * 3);
    }
    const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
    for (let i = 0; i < p.length; i++) { min[i % 3] = Math.min(min[i % 3], p[i]); max[i % 3] = Math.max(max[i % 3], p[i]); }
    primitive.attributes.POSITION = add(p, 'VEC3', 5126, 34962, min, max);
    primitive.attributes.NORMAL = add(n, 'VEC3', 5126, 34962, min.map(() => -1), max.map(() => 1));
    primitive.indices = add(simplified, 'SCALAR', 5125, 34963);
    const record = manifest.structures.find(s => s.id === mesh.name);
    record.sourceTriangleCount = record.triangleCount;
    record.triangleCount = simplified.length / 3;
    record.vertexCount = count;
    record.simplificationError = error;
    record.bounds = [min, max];
    triangles += record.triangleCount;
  }
  document.buffers = [{byteLength}];
  document.asset.generator += ' / meshoptimizer 0.22 simplification';
  let json = Buffer.from(JSON.stringify(document));
  json = Buffer.concat([json, Buffer.alloc((4 - json.length % 4) % 4, 32)]);
  const bin = Buffer.concat([...arrays, Buffer.alloc((4 - byteLength % 4) % 4)]);
  const header = Buffer.alloc(20), binHeader = Buffer.alloc(8);
  header.writeUInt32LE(0x46546c67, 0); header.writeUInt32LE(2, 4); header.writeUInt32LE(28 + json.length + bin.length, 8); header.writeUInt32LE(json.length, 12); header.writeUInt32LE(0x4e4f534a, 16);
  binHeader.writeUInt32LE(bin.length, 0); binHeader.writeUInt32LE(0x004e4942, 4);
  const output = Buffer.concat([header, json, binHeader, bin]);
  await writeFile(file, output);
  info.url = info.url.split('?')[0] + '?v=' + createHash('sha256').update(output).digest('hex').slice(0,12);
  info.bytes = 28 + json.length + bin.length;
  info.triangleCount = triangles;
  console.log(layer, info.bytes, 'bytes;', triangles, 'triangles');
}
await writeFile(manifestURL, JSON.stringify(manifest, null, 2));
await writeFile(new URL('src/data/atlasManifest.ts', root), 'import type { AtlasManifest } from "../types/atlas";\n// Generated by the import and optimization scripts.\nexport const atlasManifest: AtlasManifest = ' + JSON.stringify(manifest, null, 2) + ';\n');
